# Generated by Django 3.2.18 on 2023-04-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WineList',
        ),
    ]
