# Generated by Django 3.2.18 on 2023-04-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('antipasti', 'Antipasti'), ('main_courses', 'Main Courses'), ('dessert', 'Dessert'), ('red_wine', 'Red Wine(glass)'), ('white_wine', 'White Wine(glass)'), ('beers', 'Beers'), ('soft_drinks', 'Soft Drinks'), ('hot_drinks', 'Hot Drinks')], max_length=20),
        ),
    ]
