# Generated by Django 3.2.18 on 2023-04-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('date', models.DateField()),
                ('people', models.IntegerField()),
                ('time', models.TimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
