# Generated by Django 3.2.18 on 2023-04-27 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='register_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(choices=[(2, '2 People'), (3, '3 People'), (4, '4 People'), (5, '5 People'), (8, '8 People'), (10, '10 People')]),
        ),
    ]
