# Generated by Django 3.2.18 on 2023-04-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_auto_20230427_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.CharField(default=' ', max_length=2500),
        ),
    ]
