# Generated by Django 3.2.18 on 2023-05-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0004_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
